### ISSUE TITLE
A test demo

### ISSUE THREAD

**Issue by chengwei0427** [YungeCui/BoW3D#2]
Hi, @YungeCui 
A test demo is released at [BoW3D-LeGO-LOAM](https://github.com/chengwei0427/BoW3D-LeGO-LOAM).

The result is not very good with velodyne-16. Maybe some parameters need to be adjusted.

**Comment by YungeCui** [comment]
Yes, the parameter nScans of LinK3D need to be set as 16

**Comment by YungeCui** [comment]
Yes, the parameter nScans of LinK3D needs to be set as 16

**Comment by chengwei0427** [comment]
> Yes, the parameter nScans of LinK3D needs to be set as 16

nScans = 16. But the result is not good.

**Comment by zouyajing** [comment]
Hi ChenWei.
Does it work well after tuning parameters with VLP-16 ?

**Comment by chengwei0427** [comment]
> 



> Hi ChenWei. Does it work well after tuning parameters with VLP-16 ?

not very well.
